[build]
  publish="public"
  command="npm run debug"

[[redirects]]
  from = "/feed/"
  to = "/feed.xml"
  status = 200

[[redirects]]
  from = "/uses/"
  to = "https://kit.co/josephrexme/home-office"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
    X-XSS-Protection = "1; mode=block"