[build]
  publish = "public"
  command = "cp ./libx86/* node_modules/canvas/build/Release && npm run debug"

[functions]
  directory = "serverless"

[[redirects]]
  from = "/feed/"
  to = "/feed.xml"
  status = 200

[[redirects]]
  from = "/uses/"
  to = "https://kit.co/josephrexme/home-office"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'; object-src 'none'; base-uri 'none'; script-src 'unsafe-inline' https:;"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
